### ISSUE TITLE
Replace blocking web request listeners

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#100]
> Instead of programmatically reading network requests and altering them (as you did in Manifest V2), your extension specifies rules that describe actions to perform when a given set of conditions is met.
> - [Update permissions](https://developer.chrome.com/docs/extensions/develop/migrate/blocking-web-requests#update-permissions)
> - [Create declarative net request rules](https://developer.chrome.com/docs/extensions/develop/migrate/blocking-web-requests#create-dnr-rules)

### Code
- Search : [.addListener](https://github.com/search?q=repo%3Alingua-libre%2FSignIt%20.addListener&type=code)
  - Code [1]: [background-script.js#L335-L352](https://github.com/lingua-libre/SignIt/blob/master/background-script.js#L335-L352)
- Search : [.webRequest](https://github.com/search?q=repo%3Alingua-libre%2FSignIt%20.webRequest&type=code)
  - Code : same.

###

**Comment by kabir-afk** [comment]
The chronicle of not using `declarativeNetRequest` API can be found in #101
