### ISSUE TITLE
Enlighten available words

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#11]
This idea was floated by 0x010C.
- [x] Add a toggle button in the setting
- [x] In the page content, enlighten available words

https://stackoverflow.com/questions/67894682/how-to-add-style-for-specific-words-at-html-using-javascript
https://github.com/lingua-libre/SignIt/commit/c6cf3ada98b94c2235434966d4f9128029dc92df - example of adding a setting

**Comment by edouard-lopez** [comment]
That would be interesting, as of now, you go blind when selecting a word and often end up with nothing

The list of available words, could be updated daily (via service worker) as it's now updated that often, and store locally (local storage) then it could be used to hint add words to learn.

**Comment by hugolpz** [comment]
The list of video-documented words is provided by [`background-script.js` > `sparqlSignVideosQuery`](https://github.com/lingua-libre/SignIt/blob/master/background-script.js#L39). We miss _the function_ to html tag words within the page, likely by some kind of : 
```html
<i class="sign-it-enlighten">carbe</i>
```

```css
i.sign-it-enlighten { background-color: ##FFFF0055; }
```
As I'm now in coding pause I won't do R&D. But if you provide that function I may include it, test it, and add relevant settings.

**Comment by hugolpz** [comment]
After 3 weeks, current code seems resilient enough.
Open new issue if limitations emerges.
