### ISSUE TITLE
Fix iframe CSS

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#110]
### Concerned files
-  [./SignItVideosGallery.js](https://github.com/lingua-libre/SignIt/blob/master/SignItVideosGallery.js) -- generate the gallery, with previous/next arrows, iframe, and credits ; pass parameters via url parameters to the iframe.
- [./SignItVideosIframe.html](../blob/master/SignItVideosIframe.html) -- handle the iframe's content, can receive url parameters to set the iframe's size

### Action
- [x] Make iframe border invisible / seemless
- [x] Ensure sizes of iframe and video elements are complementary
  - mix of `width:250px`  for the iframe ; then `width:100%` inside the iframe ?)
- [x] Check result is elegant for modal, popup, and wpintegration (ex: on [Crabe](https://fr.wikipedia.org/wiki/Crabe))
- [x] Position the arrows over the iframe-video, like for Wikipedia galleries, [example](https://zh.wikipedia.org/wiki/萨诺斯龙属#/media/File:Thanos_Marvel_VS_Thanos_simonattoi_size_comparison.svg)

This is  likely a classic need with answers online or via ChatGPT-likes.

### Current state
All those states are derivated from the 2 files cited above. (My connexion was very slow so the video are black but they are working fine).

#### Modal
![image](https://github.com/user-attachments/assets/ffc4b60b-4c2c-48ea-bab7-0a4448176290)
#### Popup
![image](https://github.com/user-attachments/assets/1e193801-bd43-45f6-9915-76e7aa71335f)
#### wpintegration
![image](https://github.com/user-attachments/assets/0381f71b-7a0c-4e75-ae50-f54f32fbfd2d)
#### Arrows over video
![Screenshot_2024-07-23-09-52-50-79_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/fa1dfbe9-8ab7-4273-8c1e-ab76e0e75936)

**Comment by saltykheera** [comment]
asign this issue to me

**Comment by hugolpz** [comment]
Hello @saltykheera , happy to see you around. 
Given your enthusiasm I assigned this issue to you. 👍🏼

**Comment by hugolpz** [comment]
Secondary quest : position the arrows over the video, like for Wikipedia galleries, [example](https://zh.wikipedia.org/wiki/萨诺斯龙属#/media/File:Thanos_Marvel_VS_Thanos_simonattoi_size_comparison.svg)
![Screenshot_2024-07-23-09-52-50-79_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/fa1dfbe9-8ab7-4273-8c1e-ab76e0e75936)

**Comment by saltykheera** [comment]
[screen-recorder-fri-jul-26-2024-18-27-32.webm](https://github.com/user-attachments/assets/506587d6-6019-47a3-bf17-a07ee94eb9f8)


@hugolpz does this type of design works for the btns ?

**Comment by hugolpz** [comment]
Hello @saltykheera ,
Nice pick for the song clip.
(1) Can you  share the code ?
(2) Our Gallery with prev/next > iframe > video element approach is a bit weird it's better if you work on the extension directly. Were you able to load SignIt and inspect the video gallery ? (the thing which contains the iframe)
(3) For prev/next let's follow the [no chratjunk principle](https://en.wikipedia.org/wiki/Chartjunk), minimize the noise and remove `prev` and `next`.

**Comment by hugolpz** [comment]
After verification, the generated html has the following structure : 
```html
<div class="signit-inline-container">

  <!-- Added comment: arrow prev -->
  <span class="oo-ui-widget ..." aria-disabled="true">
    <a class="oo-ui-buttonElement-button" ...>
      ... (prev)
    </a>
  </span>
  <div class="signit-panel-videos-gallery">
    <!-- Added comment: iframe 1 -->
    <div style="">
      <iframe ...></iframe>
      par Yug – Vidéo 1 sur 4
    </div>
    <!-- Added comment: iframe 2 -->
    <div style="display: none;">
      <iframe ...></iframe>
      par Elix – Vidéo 2 sur 4
    </div>
    <!-- Added comment: iframe 3 -->
    <div style="display: none;">
      <iframe ...></iframe>
      par Caroline – Vidéo 3 sur 4
    </div>
    <div style="display: none;">
      <iframe ...></iframe>
      par Roy Batty 82 – Vidéo 4 sur 4
    </div>
  </div>
  
  <!-- Added comment: arrow next -->
    <span class="oo-ui-widget ..." aria-disabled="true">
    <a class="oo-ui-buttonElement-button" ...>
      ... (prev)
    </a>
  </span>
</div>
```

I know it relies on ./SignItVideosGallery.js (gallery with prev/next and list of iframe), ./SignItVideosIframe.html (iframe and video). After inspecting it also relies on ooui.js (to generage the html buttons), oojs-ui-wikimediaui.min.css.and content_script/wpintegration.css

**Comment by saltykheera** [comment]
@hugolpz check if this works fine for now then
if all ok i will create a PR

**Comment by hugolpz** [comment]
Let me check this tonight. ✌🏼

**Comment by kabir-afk** [comment]
Completed in referenced PR above 🎉🎉

**Comment by hugolpz** [comment]
Thank you for this push forward, screenshots below is what I get from PR #119.


### Chrome
![Screenshot from 2024-08-21 11-58-22](https://github.com/user-attachments/assets/d6e8666a-a069-4502-9248-7bc6b95e5253)

### Firefox
![Screenshot from 2024-08-21 12-01-52](https://github.com/user-attachments/assets/f318f8f5-8a53-4e41-85c2-2437e107e4e4)

### Room for progress
I still see room for progress so I'm doing a rapid push as well.

Example :
![image](https://github.com/user-attachments/assets/60da82cf-feb0-4c8a-9eb1-6a9067bdfac3)
