### ISSUE TITLE
Sponsors section

### ISSUE THREAD

**Issue by Pyb75** [lingua-libre/SignIt#12]
Si on commence à communiquer sur l'extension, ça serait bien de rajouter le nom de Wikimédia à France à quelques endroits

- [x] Collect logos
- [x] Create section. Maybe just a link to [Wikimedia > SignIt # Sponsors](https://meta.wikimedia.org/wiki/Lingua_Libre/SignIt)
- [x] Integrate section
 
## Sponsors 
- Wikimedia France
- SICD / URFIST Occitanie

## Developers
- 0x010C
- Hugolpz
- Kabir-afk

## Thanks
- ELIX, France : for sharing 100 videos, then developing their own version of the project we designed under private licence.
- IRIS, Toulouse, France : for producting signed videos
- Amélie Barrio, URFIST Occitanie : for supporting this inclusivity project.

**Comment by hugolpz** [comment]
Dans paramètre, un petit texte flottant en bas à droite. Ou en bas au millieu.
Type "Made with <3 by Wikimedia France"

**Comment by hugolpz** [comment]
@saltykheera thank you for the push, I will add one more sponsor before to close this issue.

**Comment by hugolpz** [comment]
Done by @saltykheera
