### ISSUE TITLE
Button to submit corrections

### ISSUE THREAD

**Issue by Pyb75** [lingua-libre/SignIt#13]
Si l'extension commence à être pas mal utilisé, faudra sans doute ajouter un bouton de signalement. Mais faudra voir qui est capable de traiter ces signalements. Cet ajout peut attendre la phase où l'extension existera aussi sur Chrome.

**Comment by hugolpz** [comment]
Je pense qu'il y a des urls avancées permetant ouvrir une section et d'ajouter du contenu à une page.
Un tel lien permettrait aux utilisateurs de SignIt d'ajouter les mots à une liste existante en quelques clicks.
Je ne me souviens plus comment on fait. Il me semble que l'on peut voir ceci sur l'atelier graphique ou sur le microfi, lorsqu'on soumet une demande.

**Comment by saltykheera** [comment]
@hugolpz 
![report_button](https://github.com/lingua-libre/SignIt/assets/142778969/8659a520-5eeb-4d9b-ba54-41bcdda7b298)
are u guys discussing about this section
![form_report](https://github.com/lingua-libre/SignIt/assets/142778969/313f76fb-b4e7-472e-beb4-a575c886cdc7)
is this the result u are looking for ?

**Comment by saltykheera** [comment]
To process correction submissions, we might need server storage.
Alternatively, user correction reports could be sent to a Discord channel for review and investigation.

**Comment by hugolpz** [comment]
Make it simple: just `<a href="" target="blank"></a>` opening a wiki page in edit mode so the user can type its report. So the main question here is where in the popup to put this link, which css, which text label.

**Comment by saltykheera** [comment]
@hugolpz 
assign this issue to me so i can work on it

**Comment by saltykheera** [comment]
![image](https://github.com/user-attachments/assets/8a2069d5-06c6-4dc0-9b01-3cf865f3906d)

@hugolpz is this good enough ?

**Comment by saltykheera** [comment]
#111 added enhacement in the same pr
