### ISSUE TITLE
Add configuration to replay video automatically

### ISSUE THREAD

**Issue by edouard-lopez** [lingua-libre/SignIt#14]
## Current usage

When watching a new sign, I often play it several times to help me learn it.

## Feature request

Let me replay video automatically so I can learn it more easily. Ideally, the 2nd play would be slower than the first one.

**Comment by hugolpz** [comment]
https://github.com/lingua-libre/SignIt/commit/c6cf3ada98b94c2235434966d4f9128029dc92df and published.
