### ISSUE TITLE
Add way to control video speed

### ISSUE THREAD

**Issue by edouard-lopez** [lingua-libre/SignIt#15]
## Current usage

As a person that sign casually, when watching a new sign, I often find myself trying to decompose the movement, but at normal speed it's not easy. 

## Feature request

Having the control to slow down the video would be helpful. Either on a per video (inside the player) or for all videos

**Comment by hugolpz** [comment]
File to edit is [SignItVideosGallery.js](../blob/master/SignItVideosGallery.js). It mainly creates a gallery and does little to set the video player.

Wikimedia [just announced](https://diff.wikimedia.org/2022/07/27/wikimedia-media-playback-now-brought-to-you-with-video-js/) the adoption of [Video.js]. This library has [`playbackRate`](https://videojs.com/advanced/?video=disneys-oceans) to control speed.

Note: that library will be present on Wikimedia websites (creating js conflict ?) but not on others.

**Comment by hugolpz** [comment]
https://github.com/lingua-libre/SignIt/commit/c6cf3ada98b94c2235434966d4f9128029dc92df

**Comment by hugolpz** [comment]
#14 add douple play with normal / slow (x0.5), satisfying most of the need.

Add fine control of speed would add tuning complexity to an add-on which should stay extremely basic.

**Comment by edouard-lopez** [comment]
Could you add a screencast, I don't have double speed despite the option unable

SignIt Version: `1.0.8`
Firefox version: `103.0 (64-bit)`

## Preview
![signit no double speed](https://user-images.githubusercontent.com/1212392/182123275-894cec34-91fc-49cf-9240-927100124dd6.gif)

**Comment by hugolpz** [comment]
It's not activated by default. Need to open settings, turn it off, turn it on. Better support in the coming 1.0.9.

**Comment by hugolpz** [comment]
1.0.9 published.

**Comment by edouard-lopez** [comment]
Toggling off and on did the try! :v:

**Comment by hugolpz** [comment]
Should be working natively since 1.0.9.
