### ISSUE TITLE
Make banana.i18n work across the whole web extension

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#19]
_This is tricky and may require special training on extension debugging._

Given we work in the context of a Firefox/Chrome extension, some scripts don't have access to the i18n variables (`banana`) déclared in `background-script.js`, they are therefore hard coded in English or French. Most notably the file `SignItCoreContent.js`, which is called from `popup/popup.js` and `content_scripts/signit.js` can't access `banana` (is undefined), the i18n doesn't work there. I tried `async` + `await` loading as in `popup.js`, but switching the whole code to `async` create a `result is non-structured-clonable data` error. I was unsuccessful to provide `banana` . Maybe providing the `banana` as parameter would work.

**Comment by hugolpz** [comment]
NOTE: while the code currently pass the banana-i18n via `.sendMessage()`, which could then be passed as parameter to following functions...

Additional i18n require to rethink the Modal creation / updage, likely by destroying / recreating it at `changeLanguage(uiLanguage)`. This require a fresh mind and one or two day

**Comment by hugolpz** [comment]
@kabir-afk , I assigned you this ticket since you made noticeable progress on this already.
All knowledge related to i18n should come here. Feel free to edit/delete my message : the less text we have, the most readable it will be when we come back to it.

**Comment by kabir-afk** [comment]
I was reading up on cross browser docs and I stumbled upon `browser.i18n` API. Is there a reason why we didn't use it ? Since importing the i18n functionality is a mess for now and the one provided by the browser(FF) is compatible with other browsers like chrome as well in majority of aspects like internationalizing `manifest.json` or i18n methods,etc....altho directory structure would have to be modified and it can be a lot of work but maybe it is a good alternative ?
**Resources** 

- [Chrome workflow](https://developer.chrome.com/docs/extensions/reference/api/i18n)
- [FireFox workflow](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization)

**Comment by hugolpz** [comment]
From memory, `banana.i18n` paths and file structure is wikitranslate.net-compatible, which `browser.i18n` is not.

| banana.i18n | wikitanslate.net | browser.i18n
|---|---|---
| [Banana File format](https://github.com/wikimedia/banana-i18n?tab=readme-ov-file#banana-file-format) | source | [source](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization)
| `i18n/en.json` | `i18n/en.json` | `_locales/en_GB/messages.json`

**Comment by kabir-afk** [comment]
OK...understandable 👍....can you also clarify where else I have to make the `i18n` functionality available ?

**Comment by hugolpz** [comment]
In term of final UI:
- Modal
- Popup

In terms of panels :
- videos
- definitions
- browse
- history
- settings

**Comment by kabir-afk** [comment]
Ok , so basically `popup.js` , `SignItCoreContent.js` and `SignItVideosGallery.js`

**Comment by hugolpz** [comment]
The last element missing seems :
- https://github.com/lingua-libre/SignIt/blob/master/SignItVideosGallery.js#L38
- https://github.com/lingua-libre/SignIt/blob/master/i18n/en.json#L12

From memory there is a trap. Or at least, this string is more complex since it has variable to pass to it.

**Comment by hugolpz** [comment]
```diff
! IMPORTANT : Wikimedia banana.i18n was removed following GSoC24. See also #84 .
```

See also #84 .
