### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by Pyb75** [lingua-libre/SignIt#2]
- [ ] Enquire display bugs
- [ ] Redeploy.

## Bug reported by @Pyb75
Sur lemonde.fr, le popup ne s'affiche pas correctement
![Screenshot_2019-11-08 Algérie, Liban, Irak, Chili, Hongkong La contestation est mondiale](https://user-images.githubusercontent.com/11270285/68496181-03a5e900-0252-11ea-94ae-cf56648a5302.png)

Pyb75 bug suspected to be css related.

**Comment by edouard-lopez** [comment]
Had a similar bug where the pop-in was below content

**Comment by hugolpz** [comment]
May be due to the z-index on specific sites. 😣

**Comment by hugolpz** [comment]
Seems ok as of now (2022, SignIt 1.03). I guess it was an issue on Lemonde.fr's side.
![Screenshot_20220724_104913](https://user-images.githubusercontent.com/1420189/180639714-12e55750-e43a-43d5-99f3-cf16c9194de9.png)
