### ISSUE TITLE
Migrate to manifest.json v3.0

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#21]
This actually implies to do a bunch of code migration, with `async`, etc.

## Chrome's migration checklist
Chrome provides a [migration checklist](https://developer.chrome.com/docs/extensions/develop/migrate/checklist) which points to more actionable resources :
- [x] [Update the manifest](https://developer.chrome.com/docs/extensions/develop/migrate/checklist#update_the_manifest) : [manifest.json](https://github.com/lingua-libre/SignIt/files/13614080/manifest.json), fix syntactic error warnings. 
- [x] Update your code
  - [x] [Migrate to a service worker](https://developer.chrome.com/docs/extensions/develop/migrate/checklist#migrate_to_a_service_worker)
  - [x] #98 [Update API calls](https://developer.chrome.com/docs/extensions/develop/migrate/checklist#update_api_calls) 
  - [x] #100
  - [x] Improve extension security
- #85

## V3 from scratch ?
- [Crxjs : versatile](https://crxjs.dev/vite-plugin/)
- [Templates: versatile](https://github.com/guocaoyi/create-chrome-ext)
- [React](https://github.com/lxieyang/chrome-extension-boilerplate-react)
- [React + vite](https://github.com/Jonghakseo/chrome-extension-boilerplate-react-vite)

## Resources
- [Firefox > Manifest V3 migration guide](https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/)
- [Chrome > Migrating to Manifest V3](https://developer.chrome.com/docs/extensions/mv3/mv3-migration/)
- [Extension Manifest Converter](https://github.com/GoogleChromeLabs/extension-manifest-converter)

## Related
- #32 -- require v3 before to move forward.

**Comment by hugolpz** [comment]
Manifest migrated.
[manifest.json](https://github.com/lingua-libre/SignIt/files/13614080/manifest.json)


More to migrate on the code. See [this page and following pages](https://developer.chrome.com/docs/extensions/develop/migrate/blocking-web-requests).

**Comment by hugolpz** [comment]
You can now [use both](https://stackoverflow.com/a/78088358/1974961) when coding and testing locally, thank to [YujiSoftware](https://stackoverflow.com/users/1932017/yujisoftware):

```json
"background": {
    "service_worker": "background.js",
    "scripts": ["background.js"]
},
```

EDIT: remove `"scripts": ["background.js"]` when packaging your webext for Chrome Web store. Thank to [wolfmanstout](https://github.com/wolfmanstout) for this hint.

Source: https://github.com/mozilla/web-ext/issues/2532#issuecomment-1992345597

**Comment by kabir-afk** [comment]
Mind reviewing the [PR](https://github.com/lingua-libre/SignIt/pull/63)  if you are free now😅,I mentioned the same under "Additional Info on Cross browser background scripts"😅

**Comment by kabir-afk** [comment]
When **migrating to service worker** , we have to convert timers to alarms as well. And under **Updating API calls** we have to convert `callbacks` to `Promises`. I haven't converted timers to alarms yet and I haven't looked upon the latter.

**Comment by hugolpz** [comment]
@kabir-afk , this "Replace blocking web request" item doesn't applies to us from my understanding.
![image](https://github.com/lingua-libre/SignIt/assets/1420189/e15ae7ce-457f-4478-99d6-effeecdf0957)

**Comment by hugolpz** [comment]
I close this. We consider it done since is works correctly with MV3 approach.

If Chrome / Firefox stores requests changes, it will be to adapt to those stores' requirements, and new issues must be open.
