### ISSUE TITLE
Issues with the qqq.json documentation

### ISSUE THREAD

**Issue by Abijeet** [lingua-libre/SignIt#25]
I noticed the following issues with the qqq.json file:

- [x] Please remove the keys that don't have any content. Eg: `"si-popup-settings-uilanguage-help":"",`
- [x] Remove key - `"si-overlay-coreContent-right--wikt-section-id":"",` that has no entry in the `en.json` file.

**Comment by hugolpz** [comment]
Solved. I added the proper content to 1) and fixed the naming error in 2).
