### ISSUE TITLE
Update project documentation

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#3]
### Update manifest
- [x] Update manifest.json with new urls

### Improve documentation
- [x] Expand readme.md : How to install on my computer ?
- [x] Expand readme.md : add description from available resources (Firefox add on description)
- [x] Add `doc` folder, add screenshots from available resources (Firefox add on description)

@edouard-lopez : do you actively use this project ? Could you share some visuals ?

**Comment by edouard-lopez** [comment]
On Firefox I can't get a list of word nor a definition even for word from [Category:Videos_Langue_des_signes_française](https://commons.wikimedia.org/wiki/Category:Videos_Langue_des_signes_fran%C3%A7aise)

![image](https://user-images.githubusercontent.com/1212392/106491803-89e1c700-64b7-11eb-9133-d9ce290359a2.png)

![image](https://user-images.githubusercontent.com/1212392/106491927-a8e05900-64b7-11eb-844a-0a60fa2e5a1b.png)

**Comment by hugolpz** [comment]
- [x] Update tasks closed.
- [x] Display bug moved to #2
