### ISSUE TITLE
Settings toggles to migrate to checkboxes

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#35]
Half of current settings rely on large, double-line [OO.ui.ToggleSwitchWidget](https://doc.wikimedia.org/oojs-ui/master/js/#!/api/OO.ui.ToggleSwitchWidget) :
- `wpintegration`
- `twospeed`
- `hinticon`
- `coloredwords`
- `showvideo`

See [./popup/popup.js](https://github.com/lingua-libre/SignIt/blob/master/popup/popup.js#L208-L241).

We could migrate to single-line checkboxes elements such as
- [OO.ui.CheckboxInputWidget](https://doc.wikimedia.org/oojs-ui/master/js/#!/api/OO.ui.CheckboxInputWidget)
- [OO.ui.CheckboxMultiselectWidget](https://doc.wikimedia.org/oojs-ui/master/js/#!/api/OO.ui.CheckboxMultiselectWidget)
- [OO.ui.CheckboxMultiselectInputWidget](https://doc.wikimedia.org/oojs-ui/master/js/#!/api/OO.ui.CheckboxMultiselectInputWidget)

The differences of usage of those later 3 must be studied before implementation.

Also : should we do this ? This change would create 2 status in the setting, some larger 2-lines options, and some smaller single-line options. 
Is this an acceptable UI/UX practice ?

See also : #36 

| Current | Suggested |
| ---- | ---- |
| ![Screenshot from 2023-06-13 16-21-49](https://github.com/lingua-libre/SignIt/assets/1420189/ed588c42-94b0-4e4a-ab56-07a7c8471a5e) | ![Screenshot from 2023-06-13 16-21-35](https://github.com/lingua-libre/SignIt/assets/1420189/6bfb1691-704f-447c-bc7d-f1cfbba5d108) |

**Comment by saltykheera** [comment]
assign me this issue

**Comment by hugolpz** [comment]
@saltykheera Done.

**Comment by ayushanand308** [comment]
@hugolpz @saltykheera  I can work on this if anyone is currently not

**Comment by hugolpz** [comment]
Hello @ayushanand308, you are welcome to do so. You know a bit about Wikimedia's oojs ?

Please note : This issue is purely UI-related. In 2024, we wish to totally revamp this web extension. So your efforts on this issue, while welcome if you enjoy coding it and learning on the way as I sometime do, could be replaced in late 2024 by a new UI.

**Comment by pushkar707** [comment]
Okay, I understand the issue, and the main motive behind switching from toggle switched to checkboxes seems to be saving to of lines and space, right? I will start working over it.

I would also check these before starting:

[OO.ui.CheckboxInputWidget](https://doc.wikimedia.org/oojs-ui/master/js/#!/api/OO.ui.CheckboxInputWidget)
[OO.ui.CheckboxMultiselectWidget](https://doc.wikimedia.org/oojs-ui/master/js/#!/api/OO.ui.CheckboxMultiselectWidget)
[OO.ui.CheckboxMultiselectInputWidget](https://doc.wikimedia.org/oojs-ui/master/js/#!/api/OO.ui.CheckboxMultiselectInputWidget)

**Comment by pushkar707** [comment]
This is what the checkbox looks like (Implemented using CheckboxInputWidget ):-

![Screenshot (23)](https://github.com/lingua-libre/SignIt/assets/77536989/d163cd63-2542-43f1-8559-f9ad4daa0eff)

If this is okay, I can implement it for all four toggle buttons and make a PR

I have also made the checkbox work as required, i.e. toggle the colored words functionality in this case.

**Comment by hugolpz** [comment]
@pushkar707 thank you.

From memory, you may want to inspect a bit the CSS. Those check boxes are smaller and should allow `display:inline-block`.

Ps: I spent the day initing a manifest v3 revamp, checking this new ecosystem to prepare/plan the _to do_ of 2024.

**Comment by pushkar707** [comment]
@hugolpz Thanks for assigning this issue to me. I will implement the icon-text duo via CSS, and implement a checkbox for all the toggle buttons.

Also, it so great that this project has initiate the revamp towards manifest v3.

**Comment by pushkar707** [comment]
@hugolpz please check PR #59 . I have done it
