### ISSUE TITLE
Make video and wiktionary blocks optional

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#36]
Some language communities may have and therefore need :
- only wiktionary
- both
- only the sign language videos.

Also, we would gain to make these blocks optional, based on the language ui used and user settings.
<img src="https://raw.githubusercontent.com/lingua-libre/SignIt/master/doc/LinguaLibre_SignIt-all.png"/>

### Actions
- [x] clean and normalize `SignItCoreContent.js` and popup's classes, ids names.<br>#68 
- [x] create proper panels (html structure), check for responsive html, css in SignItCoreContent.js
- [x] create initial setting and customizable settings in background.js and popup.js

**Comment by pushkar707** [comment]
Hi, I would like to do in modal toggle, how should we go about it? We can add a dropdown menu in the model to select three of the following options:-

1) Show only video
2) Show only text
3) Show both video and text.

Another approach to do this is that we have two toggle buttons as:-
1) Show/Hide Video
2) Show/Hide definition
 
Personally, I feel second approach is bit more user-friendly, but either can be done

**Comment by saltykheera** [comment]
@hugolpz i am very much interested in solving this issue.
under your guidance.

**Comment by hugolpz** [comment]
- ✅ Initial request : make individually optional panels have been satisfied.
- Declined: in-modal toggle.

### In-modal toggle
@saltykheera hello, I'm closing this ticket, I removed yours and my JS exploration for in-modal toggle.
Kabir is revamping this web extension, the toggle feature is available via the settings. 
We keep it simple in the code and on github for now.
Note: I kept your CSS within the css file since its design is witty. 👍🏼 
See f75a4187d0626a501182f7a924cb6b818ec1bb53 .
