### ISSUE TITLE
Link from the wikitionary are broken

### ISSUE THREAD

**Issue by edouard-lopez** [lingua-libre/SignIt#37]
Having the wikitionary definition is a nice addition!

However, the links broke the pop UI as they are relative to the extension

    moz-extension://cf0f4968-86f0-4896-9d0f-baeaa1a6a094/wiki/%C3%89tat

### Solutions
1. They should be fixed by prefixing them with FQDN, e.g. `https://…` 
2. render as text. 
 
My preference goes to the first solution.

[signit. wikitionary link are broken.webm](https://user-images.githubusercontent.com/1212392/191437920-7e0c8a5b-ee5d-4222-a987-e783f6cd8236.webm)

**Comment by hugolpz** [comment]
Pointer: it's around there https://github.com/lingua-libre/SignIt/blob/master/SignItCoreContent.js#L107-L118

**Comment by hugolpz** [comment]
Likely fixed int https://github.com/lingua-libre/SignIt/commit/91531855172379a07a0f756fcd375d1452d464fb .
Not deployed to the store yet.
