### ISSUE TITLE
Get back addon control

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#4]
## Current situation
[LinguaLibre SignIt is on mozilla addon store](https://addons.mozilla.org/en-US/firefox/addon/lingua-libre-signit/).
This addon is under 0x010C control and currently failling, likely due to migration from `.fr` to `.org`.
It is needed to get back control to redeploy.
![Screenshot_2021-02-04_01-35-38](https://user-images.githubusercontent.com/1420189/106827890-8e5dd980-6689-11eb-8297-559f07699232.png)

## Explore and learn
- [x] Get account on Mozilla :arrow_right: hugo.lpz ...
- [x] Explore developer tools, train, learn
- [x] Upload an alternative version of SignIt. 
- [Settings page](https://addons.mozilla.org/en-US/developers/addon/lingua-libre-signit-yug/edit#)
- [Published page](https://addons.mozilla.org/en-US/firefox/addon/lingua-libre-signit-yug/)
- [x] Download that version, test.
- [x] Edit, publish, test cycle.

## Set up development suite
- [x] Download FirefoxNightly - developers friendly
- [x] Ubuntu Install FirefoxNightly. See [here](https://blog.nightly.mozilla.org/2016/09/19/getting-firefox-nightly-to-stick-to-ubuntus-unity-dock/)
- [x] [Allows addons from file](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox#w_what-are-my-options-if-i-want-to-use-an-unsigned-add-on-advanced-users) : Open url `about:config` > search `xpinstall.signatures.required` : set to `false`
- [x] Build SignIt addon : `npm run webext`
- [x] Load SignIt addons : Open url `about:addons` > click the gear > click `Install Add-on from File...`
- [x] Open url `about:debugging#/runtime/this-firefox` > Find SignIt : click "Inspect". It opens an extension inspecting tab.
- [x] Test on Wikipedia
  - [Couscous](https://fr.wikipedia.org/wiki/Couscous) -> should show video
  - [Changer](https://fr.wikipedia.org/wiki/Changer) -> should show videos
  - [Chanter](https://fr.wikipedia.org/wiki/Chanter) -> should not show a video because none recorded.

![Screenshot_2021-02-04_01-35-08](https://user-images.githubusercontent.com/1420189/106827864-800fbd80-6689-11eb-9e8c-eb6e497802ae.png)

## Get access
- [ ] Get a dev On wikimedia.fr account created, or similar. CC: @mickeybarber 
- [x] Message 0x010C
- [x]  Get access to Hugo ?

**Comment by edouard-lopez** [comment]
Procedure is nicely documented!

**Comment by hugolpz** [comment]
Did. No answer so far. (And honestly, he warned us about is limited web access.)

**Comment by 0x010C** [comment]
The following author has been added to your addon Lingua Libre SignIt ( https://addons.mozilla.org/en-US/firefox/addon/lingua-libre-signit ):

Yug ( https://addons.mozilla.org/en-US/firefox/user/4128914 ): Developer

**Comment by hugolpz** [comment]
Hello Antoine, thank for passing by, I hope you are going well.
I'am indeed user `4128914` . Nothing so far on [my account](https://addons.mozilla.org/en-US/firefox/user/4128914/) and [SignIt page](https://addons.mozilla.org/en-US/firefox/addon/lingua-libre-signit/) at T=+22 hours. Nothing in my emails either.

* [Edit SignIt ownership here](https://addons.mozilla.org/en-US/developers/addon/lingua-libre-signit/ownership).

**Comment by hugolpz** [comment]
✅  Done : developer access given to hugolpz.

### Summary
- Edit ownership : https://addons.mozilla.org/en-US/developers/addon/lingua-libre-signit/versions
  - `Owner`: @0x010C can change access rights.
  - `Developer`: hugolpz can publish new versions from gitthub code.
- Accepting inviation: https://addons.mozilla.org/en-US/developers/addon/lingua-libre-signit/invitation when logged in.

Closing this issue. Thanks everyone ! 🙏🏼 🚀 👍🏼
