### ISSUE TITLE
Negation in sign language

### ISSUE THREAD

**Issue by Gobtous** [lingua-libre/SignIt#42]
In french sign language, for example :
* j'aime/j'aime pas (i love/ I dislike)
* je veux/je veux pas (i want/ I don't want)

Here is a video, that introduce well LSF. Joël Chalude show the "irregular" verb in french sign language :
https://invidious.fdn.fr/b3v7o6Xi5Zs?t=104

So it bring another layer of difficulty as Sign It translate words by word. So i'm not sure if Sign It can detect a negative sentence, i don't know how it works on the technical side. For now, i can only think of a toggle above the video. Where we can switch to the negative verb. As for other sign language, i don't know if they have the same irregular verb.

**Comment by hugolpz** [comment]
The question you raise is correct. But it's on the linguistic / lexicographic side, and not on the software side.
So this question will be forwarded to the contributing signers.

Second point, SignIt is not aimed at sentence translations. We do not aim to do it all. Sentence translation are an other, much harder NLP question we, a tiny volunteer-based Open content project, cannot afford to attack.

SignIt is an e-learning tool allowing learners to learn **word by word**, on basic 5000+ vocabulary. We simply increase exposure to sign languages by making it available in all webpages.

**Comment by Gobtous** [comment]
Well, i think it is a good question and i tought we could include irregular verb.

Off-topic
>Second point, SignIt is not aimed at sentence translations.

Yeah that's a question that linguist can explore and dive. Is the sign "i don't want" a word in sign language ?

"The fish is in the bowl" => translate into one sign : bowl-fish.
"He is walking fast" => one sign : walk-fast
Or the verb "To fall" => there is none because it is tied to its context. The sign "to fall" doesn't exist alone. It's a sign-environnement or sign-action. I don't have the correct word to convey it. For exemple, those signs exist "a falling leave", "a human falling from stairs" 

I understand that the aim is to raise sign language awareness. But can we add definitions in sign language for the wikitionnary ?

I want deaf people to use SignIt in their daily life and help them understanding text. So you would have an extension that is helpful for both side : hearing and Deaf.

But i understand your point. sadly i'm not a developper.

**Comment by hugolpz** [comment]
We can create and video document expression such as :
- `falling leave` or `fall (leave)` ➡️ one sign and signed video
- `human falling` or `fall in stairs` or `fall (walk)` or `fall (stairs)` ➡️ one sign and signed video
- `walking fast` or `walk (fast)` ➡️ one sign and signed video.

So those concepts and signs can be in the SignIt-Wiktionary datasets, and can be displayed when you look for "walk", "stairs", "leave", etc.

On the other side, in webpages, when working from written text, we will never ecounter `walk (fast)` and rarely `walking fast`.
This overall question of is a lexicographic question, like #38 , which is the responsibility of the lexicographer making the wordlists and the entries words conventions (`walk (fast)` or `walking fast`?). Those will be up to the signers to find out and suggest some workable solutions.

**Comment by Gobtous** [comment]
Thank a lot for your precision. ☺️

**Comment by hugolpz** [comment]
Light follow up for @Gobtous. IRIS and myself lead a video recording workshop yesterday : 
- [2024.01.17 IRIS Workshop](https://commons.wikimedia.org/wiki/Category:Lingua_Libre_pronunciation-fsl) > videos by `Hugo en résidence` (video actually from Carole).

Based on the discussion you and me had above on github, we implemented the parenthesis approach to homographs : 
- [accueil (lieu)](https://commons.wikimedia.org/wiki/File:LL-Q33302_(fsl)-Hugo_en_r%C3%A9sidence-accueil_(lieu).webm)
- [catalogue (liste)](https://commons.wikimedia.org/wiki/File:LL-Q33302_(fsl)-Hugo_en_r%C3%A9sidence-catalogue_(liste).webm)
- [conseiller (n.)](https://commons.wikimedia.org/wiki/File:LL-Q33302_(fsl)-Hugo_en_résidence-conseiller_(n.).webm)
- [conseiller (v.)](https://commons.wikimedia.org/wiki/File:LL-Q33302_(fsl)-Hugo_en_résidence-conseiller_(v.).webm)
- etc.
