### ISSUE TITLE
Upload logo proposals to Wikimédia Commons

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#45]
@saltykheera , I encourage you to upload vector versions (svg) of your logo proposals [to Wikimédia Commons](https://commons.wikimedia.org/wiki/Special:UploadWizard). We can then store them in [Category:Proposed_Lingua_Libre_logo](https://commons.wikimedia.org/wiki/Category:Proposed_Lingua_Libre_logo). Let me know if I can assign you this ticket.

**Comment by saltykheera** [comment]
@hugolpz assign i have submitted my work on [wikimedia commons](https://commons.wikimedia.org/wiki/Special:UploadWizard)

![image](https://github.com/lingua-libre/SignIt/assets/142778969/2404d63d-832b-4d8f-b78d-3ecb8f786932)

**Comment by hugolpz** [comment]
@saltykheera , I added your logos to [Category:Proposed Lingua Libre logos](https://commons.wikimedia.org/wiki/Category:Proposed_Lingua_Libre_logos).

Improvement tips: generally speaking, on open source, prefer vector formats and sharing such as .svg or .pdf. Others can edit those faster.

We are good enough, I close this issue. Thank you Salty !
