### ISSUE TITLE
v1.20

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#47]
Following @saltykheera challenge, the `choosepanels` have been implemented.
Few steps before a new release.

#### Translations
- [x] Wait one month for [translate-wiki's translations](https://translatewiki.net/wiki/Translating:Lingua_Libre_SignIt#sortable:3=desc) to come in

#### Finish #36
- [x] Clean Salty's in-modal toggle, either : 
  - [x] remove from SignItCoreContent.js + content_script/signit.css
  - [ ] rewrite with OO.ui.js in SignItCoreContent.js. Behavior should synch with localStoreage `choosepanels`.

**Comment by saltykheera** [comment]
@hugolpz i want to work on this issue.

**Comment by hugolpz** [comment]
@saltykheera hello, I'm closing this ticket, removing yours and my JS exploration for in-modal toggle.
Kabir is revamping this web extension, toggle works using the settings. We keep it simple for now.
I kept your CSS within the css file since its design is witty.
See f75a4187d0626a501182f7a924cb6b818ec1bb53 .
