### ISSUE TITLE
Popup not loading basic words.

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#5]
## Reported by @edouard-lopez
On Firefox I can't get a list of word nor a definition even for word from [Category:Videos_Langue_des_signes_française](https://commons.wikimedia.org/wiki/Category:Videos_Langue_des_signes_fran%C3%A7aise)

![image](https://user-images.githubusercontent.com/1212392/106491803-89e1c700-64b7-11eb-9133-d9ce290359a2.png)

![image](https://user-images.githubusercontent.com/1212392/106491927-a8e05900-64b7-11eb-844a-0a60fa2e5a1b.png)

## Reproducing the bug
- [x] Open Firefox (NOT nightly) > Google `Lingualibre SignIt Firefox` > Go on mozilla apps store : Install app
- [x] Open [Wikipedia's article `Changer`](https://fr.wikipedia.org/wiki/Changer) : 
  - right-click on word `changer` > SignIt
  - On top right of window : click on extension SignIt > enter `changer`.

**FETCH INDEED FAILS.**

![Screenshot_2021-02-04_01-35-38](https://user-images.githubusercontent.com/1420189/106829055-ab93a780-668b-11eb-9c09-92cbcf3eb07e.png)

**Comment by hugolpz** [comment]
## Fix & fix
Hypothesis: Bug suspected to be url related since the mid 2020 `.fr` to `.org` migration. 

Tested updating all code from `lingualibre.fr` into `lingualibre.org`, then loading the local extension on Firefox Nightly :
- `Manifest.json`
- `background-script.js`
- `popup/popup.html` ... just a link.

FETCHING NOW WORKS

![Screenshot_2021-02-04_01-35-08](https://user-images.githubusercontent.com/1420189/106827864-800fbd80-6689-11eb-9e8c-eb6e497802ae.png)

## Next
- [x] Push to github 
- [ ] #4 Get back control over the app
- [ ] Reupload on Mozila store.

**Comment by edouard-lopez** [comment]
Nice one!

**Comment by hugolpz** [comment]
I close this issue. It now depends upon #4 .
