### ISSUE TITLE
Understanding new users

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#58]
> TLDR: Following SignIt being posted on "" and [Wikimedia GSoC24](https://www.mediawiki.org/wiki/Google_Summer_of_Code/2024#9._Lingua_Libre_SignIt) , and [Lingualibre Wikimedia GSoC24](https://www.mediawiki.org/wiki/Google_Summer_of_Code/2024#10._Lingua_Libre_v3.0_enhancement_and_migration), about 7 student developpers interested by the Google Summer of Code 2024 arrived here, showing interest and curiousity. After some discussion on #58 , the Lingualibre GSoC24 apprentice selection started, mostly on Discord.

Hello @pushkar707, @shashankiitbhu, @JatinSainiOO7, @LeoDupont . cc @kabir-afk

### Understanding
In past few weeks I saw 4 new github accounts arrive on this open source Wikimedia project. I would like to understand better the reason of these arrivals and the possibilities it could open. Also may I ask you more about you and your interest in SignIt  ?

1. How did you discovered SignIt's repository ?
2.  Are you wikimedians editors ? -> which wiki projects
3. Are you developer ? -> which coding languages ?
4. What is your relation to sign languages ? -> practicing, interested, related people are practicing ?

### 2024
It's great to see this new activity and I strongly suspect it is linked with our recent GSOC exploration which is playing out this late March. I would like to understand your interest better so I may answer your needs better. Feel free to DM me if you prefer.

**Comment by shashankiitbhu** [comment]
Hi @hugolpz 

1. I got to know about this project through GSOC Idea Page for Wikimedia
2. I am a contributor in another Wikimedia Project - Commons Android App
3. I am a developer my relevant tech skills for this project includes CSS, HTML5, JavaScript
4. I am interested in it

**Comment by pushkar707** [comment]
Hi @hugolpz,

So, I got to know about the Signit project through GSOC, and I wish to work over it for GSOC internship, therefore I have been taking out my time, getting familiar with the codebase, and make contributions.

I haven't worked on any wiki projects in the past, but I have done open-source contributions before this.

I am a developer in Javascript (MERN Stack) and Python (Flask and Django). My portfolio: http://pushkarbansal.me/

I have no particular relation with sign languages, but the project seems very interesting and helpful to me personally.

**Comment by pushkar707** [comment]
Hi @hugolpz,

I was looking at the projects list of Wikimedia and I don't see Signit project there. I think the projects list has been updated.

Can you please confirm this to me?

**Comment by hugolpz** [comment]
@pushkar707  I have some paperwork ro do this weekend to get the project back on track yes. I'm on it.

**Comment by hugolpz** [comment]
@pushkar707 we have two projects in line. Poslovitch projects involves Python Django. So stay tuned. 👍🏻

**Comment by pushkar707** [comment]
@hugolpz thanks for letting me know, and also it's great to know that there's a project involving django also!

**Comment by saltykheera** [comment]
Hey @hugolpz,
I've been really intrigued by the SignIt project since 2023. I remember you noticed my previous attempts to understand the code base. I'm proficient in JavaScript, React, Node.js, Next.js, and Python. In fact, I've worked on a hackathon project where I built a sign language to text language detection system using video-to-text processing. This experience further fueled my interest in this field. Looking forward to contributing more to the SignIt project!

**Comment by pushkar707** [comment]
Hi @hugolpz, i received your mail, and created accounts you mentioned on email, 

My username is pushkar7077

I don't have push/pull access to Poslovitch repository. I saw the microtask 1, and I want to complete it as soon as I get the access to the repository.

**Comment by hugolpz** [comment]
@pushkar707, @shashankiitbhu, @JatinSainiOO7, @LeoDupont , @saltykheera . cc @kabir-afk

Hello all, following recent arrival of 5~6 users and your self introductions above or via DM I started to do my best to spread the relevant information to the right persons, and the relevant persons to the relevant project. 

Please bear with me : it wasn't clear who was here explicitly here for the GSoC2024 and who was here to chill on a cool open source project. My core idea is we are all here to get experience & fun, with different skills and constraints. When the goal is explicitly to gain professional experience, I redirect the user toward the relevant project, etc.

Where are we now ?

### [GSoC] Lingua Libre v3.0 enhancement
> [Wikimedia GSoC](https://www.mediawiki.org/wiki/Google_Summer_of_Code/2024#10._Lingua_Libre_v3.0_enhancement_and_migration) & [Wikimedia Phabricator](https://phabricator.wikimedia.org/T359797)

The larger mother project **Lingua Libre** involving Django and Vuejs skills is applying for the Google Summer of Code 2024. So I encouraged both @shashankiitbhu and @pushkar707 , who actually landed here with GSoC intership in mind and the will to acquire formal experience, to explore that Lingualibre project. Discussion about this project are lead [on Phabricator](https://phabricator.wikimedia.org/T359797) (so I will avoid this topic here).

PS: @saltykheera, you may also have a suitable Python/VueJS profile but there is only one internship there so I don't feel comfortable pointing a 3rd applicants there.

### Lingua Libre SignIt
@kabir-afk, myself and @saltykheera expressed interest for SignIt in a open source way. Lingualibre SignIt, a much smaller projet. There are minor feature requests to code and migrate to Chrome-based development. The main difficulty in 2024 for us will be to understand Web extension manifest v3.0 documentations, with its convoluted security constrains, and to lead a revamp to manifest v3. We are mostly chill about it, it's a summer 2024 objectives, but we are preparing the way.

### [GSoC] Lingua Libre SignIt
> [Wikimedia GSoC](https://www.mediawiki.org/wiki/Google_Summer_of_Code/2024#9._Lingua_Libre_SignIt) & [Wikimedia Phabricator](https://phabricator.wikimedia.org/T359799)
There is also a weaker possibility that SignIt also get a GSoC2024 modest intership, just 90 hours.
One requirement we don't meet there is the need of a 2nd technical mentor. If someone feels to do so with me, you are welcome. We can then prepare the application of one intern. 

### Synchroneous discussion
For each of you, please join [our Discord > Tech board chanel](https://discord.gg/Bqn3yXCp89) of synchroneous conversation. Be it for GSoC or for long term, chill open source contribution, we currently have a group dynamic. Rapid discussion could help move further, including on the GSoC choices.

**Comment by jatinder14** [comment]
Hi I am a full stack developer contributing to wikimedia from past few days. I can handle complex backends and frontend as well
@hugolpz

**Comment by zhjiang1103** [comment]
Hey @hugolpz, I'm really interested in contributing to the Signit project through GSOC and beyond. I'm currently pursuing a Master's degree in Computer Science at Georgia Insititute of Technology and have experience as a full-stack developer for PERN stack, along with proficiency in Python. I'm also a contributor to wikieducation. Previously, I worked in the education industry and am familiar with sign language.

**Comment by hugolpz** [comment]
Hello @zhjiang1103 , thank for your interest.
SignIt is a web-extension, it's rather a small project and small GSoC intership (2.5 weeks) for a Master degree, involving JS only. It doesn't seems to be optimal for your professional growth.
You can [contact me on our Discord > Tech board chanel](https://discord.gg/Bqn3yXCp89). Say you are Zhjiang1103 from github.

**Comment by hugolpz** [comment]
See the TLDR at the top of this issue.
