### ISSUE TITLE
Minimal test of i18n

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#86]
I just read these whole pages (5~7mins) : 
> Mozilla > Browser extension > Internationalization
> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization#direct_placeholder_usage
> API :
> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n

These are derivated from Chrome.i18n page cited below.

There are no mention of _content script_ vs _popup_ scopes or  `browser.i18n` solving this difficulty. Let's test this live. No need to undo current system, let's first see if i18n works everywhere (modal + popup ; FF + Chrome) in a more resilient way.

Read more :
- Chrome Extensions > Reference > API > [chrome.i18n](https://developer.chrome.com/docs/extensions/reference/api/i18n)

### Test JS
Add the following call to i18n values :  
```js
// Somewhere in popup > settings
browser.i18n.getMessage("si_addon_title");
// Somewhere in video gallery
browser.i18n.getMessage("si_panel_videos_gallery_attribution", ['https://link.to/video', 'CreatorName', '2', '4']);
```

### Test manifest.json
In `manifest.json`, try replacing `name`'s value. Note: maybe the `name` key's snake_case will mess with that, but need to be tester.
```json
"name": "__MSG_si_addon_title__",
```

### Go further
[How to Add Internationalization (i18n) to Your Chrome Extension: Guide](https://www.stefanvd.net/blog/2023/04/24/how-to-add-internationalization-i18n-chrome-extension/#step-2-add-i-18-n-messages-to-your-manifest-file) (5mins) also provides a step by step migration guide. Importantly, it provides some refresh i18n code sample to learn from.

### See also
- #84 If current issue successful and easy, then move forward.

## Results

| Scope | Chrome | Firefox |
| --- | --- | --- |
| Popup > Settings  | ✔ | ✔ |
| Popup > Browse > video gallery | ✔ | ✔ |
| Content script > modal > video gallery  | ✔ | ✔ |

**Comment by kabir-afk** [comment]
I am currently reading docs , and I feel that the popup UI refresh bug wont be an issue as we wont be relying on local storage then. Another thing I wanted to address is that , many methods under `browser.i18n` aren't supported in Safari , is that ok ?

**Comment by hugolpz** [comment]
Yes, it's ok. We are on Desktop extension as of 2024. 
#32 and [source](https://analytics.wikimedia.org/dashboards/browsers/#all-sites-by-browser/browser-family-and-major-tabular-view) shows :

|Date | Browser | Market share
|--- |---|---|
| 2024-03-31| Safari |2.1%

**Comment by kabir-afk** [comment]
I also observed that while `browser.i18n` can substitute values with placeholders , it doesn't additionally parse like `banana.i18n` did.  For example -  `banan.i18n({{link|$1|$2}})` got parsed into something like `<a href="$1">$2</a>`. But native API doesn't provide that, so we'd still have to do some labor of our own.

**Comment by hugolpz** [comment]
From what I read, with [Direct placeholder usage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Internationalization#direct_placeholder_usage) , the following should work :

```json
 "si_panel_videos_gallery_attribution": {
    "message": "by {{link|$1|$2}} – Video $3 of $4",
    "description": ""
  },
```
and 
```js
browser.i18n.getMessage("si_panel_videos_gallery_attribution", ['https://link.to/video', 'CreatorName', '2', '4']);
```
Should produce :
```html
by {{link|https://link.to/video|CreatorName}} – Video 2 of 4
```

But this is ok ! We can then edit the json files to replace `{{link|$1|$2}}` by `<a href="$1">$2</a>` and it will work fine.

**Comment by kabir-afk** [comment]
Agreed, but `by {{link|https://link.to/video|CreatorName}} – Video 2 of 4` is not something we want right ? We want the actual hyperlink. I was just mentioning it , and instead of changing keys in all the files maybe we parse it directly inside `SignItVideosGallery.js` like we did earlier.

**Comment by hugolpz** [comment]
Let's fully move to full html. This `{{link|}}` shorthand adds complexity with no gain.

**Comment by hugolpz** [comment]
This is good news !

![Image](https://github.com/lingua-libre/SignIt/assets/1420189/71d5a7c7-faea-4178-9faf-6ce90b4f2fdd)

**Comment by kabir-afk** [comment]
Yea well I have done that already inside the `refresh` prtotype method. But since we were only testing I thought of keeping the previous `banana.i18n` methods. Should I remove them from all the other files as well ? Is it finalized that we are migrating from `banana.i18n` to `browser.i18n`
