### ISSUE TITLE
Migrate from callback to promise

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#98]
See https://developer.chrome.com/docs/extensions/develop/migrate/api-calls#replace-callbacks

Affects :
- #21.

**Comment by kabir-afk** [comment]
@hugolpz how will it affect #66 ?

**Comment by hugolpz** [comment]
How, from your Discord message I though you told me so.

**Comment by kabir-afk** [comment]
Naah , I was referring to extension API methods which used callbacks. They needed to be replaced with promises , as mentioned in the docks.

**Comment by hugolpz** [comment]
Ok, thanks good. Because I did look at those .sendMessage table and I didn't got how it was related to my xhr + endpoint fetch.

**Comment by hugolpz** [comment]
Deleted 4 clarification comments with no added value.
